INSERT INTO `temporary_models` (`Make`, `Model`) VALUES
('AC', '212'),
('AC', 'Ace'),
('AC', 'Aceca'),
('AC', 'Cobra'),
('AC', 'Superblower'),
('Alfa Romeo', '145'),
('Alfa Romeo', '146'),
('Alfa Romeo', '147'),
('Alfa Romeo', '147 3-door'),
('Alfa Romeo', '147 5-door'),
('Alfa Romeo', '155'),
('Alfa Romeo', '156'),
('Alfa Romeo', '159'),
('Alfa Romeo', '164'),
('Alfa Romeo', '166'),
('Alfa Romeo', '33'),
('Alfa Romeo', '75'),
('Alfa Romeo', '90'),
('Alfa Romeo', 'Alfasud'),
('Alfa Romeo', 'Alfetta'),
('Alfa Romeo', 'Arna'),
('Alfa Romeo', 'Brera'),
('Alfa Romeo', 'Giulietta'),
('Alfa Romeo', 'Gold Cloverleaf'),
('Alfa Romeo', 'GT'),
('Alfa Romeo', 'GTV'),
('Alfa Romeo', 'Mito'),
('Alfa Romeo', 'Spider'),
('Alfa Romeo', 'Sprint'),
('Alfa Romeo', 'SZ'),
('Asia', 'Rocsta'),
('Aston Martin', 'DB7'),
('Aston Martin', 'DB9'),
('Aston Martin', 'DBS'),
('Aston Martin', 'Lagonda'),
('Aston Martin', 'V8'),
('Aston Martin', 'V8 Vantage'),
('Aston Martin', 'V8 Vantage Roadster'),
('Aston Martin', 'Vanquish'),
('Aston Martin', 'Vantage'),
('Aston Martin', 'Virage'),
('Aston Martin', 'Volante'),
('Audi', '100'),
('Audi', '200'),
('Audi', '400'),
('Audi', '500'),
('Audi', '80'),
('Audi', '90'),
('Audi', 'A2'),
('Audi', 'A3'),
('Audi', 'A4'),
('Audi', 'A4 Avant'),
('Audi', 'A4 Cabriolet'),
('Audi', 'A4 Sedan'),
('Audi', 'A5'),
('Audi', 'A6'),
('Audi', 'A8'),
('Audi', 'Allroad'),
('Audi', 'Cabriolet'),
('Audi', 'Convertible'),
('Audi', 'Coupe'),
('Audi', 'Q5'),
('Audi', 'Q7'),
('Audi', 'Quattro'),
('Audi', 'R8'),
('Audi', 'RS2 Avant'),
('Audi', 'RS4 Avant'),
('Audi', 'RS4 Quattro'),
('Audi', 'RS6'),
('Audi', 'S2'),
('Audi', 'S3'),
('Audi', 'S4'),
('Audi', 'S5'),
('Audi', 'S6'),
('Audi', 'S8'),
('Audi', 'TT'),
('Audi', 'Turbo'),
('Austin', 'Allegro'),
('Austin', 'Ambassador'),
('Austin', 'Healey'),
('Austin', 'Maestro'),
('Austin', 'Maxi'),
('Austin', 'Metro'),
('Austin', 'Mini'),
('Austin', 'Montego'),
('Austin', 'Princess'),
('Baracuda', 'Valiant'),
('Beach', 'Buggy'),
('Bentley', 'Arnage'),
('Bentley', 'Azure'),
('Bentley', 'Brooklands'),
('Bentley', 'Continental'),
('Bentley', 'Corniche'),
('Bentley', 'Eight'),
('Bentley', 'Mulsanne'),
('Bentley', 'Series II'),
('Bentley', 'Turbo R'),
('Bentley', 'Turbo RT'),
('BMW', '1-Series'),
('BMW', '1-Series 3-Door'),
('BMW', '1-Series 5-Door'),
('BMW', '1-Series Convertible'),
('BMW', '1-Series Coupe'),
('BMW', '3-Series'),
('BMW', '3-Series Compact'),
('BMW', '3-Series Convertible'),
('BMW', '3-Series Coupe'),
('BMW', '3-Series E46'),
('BMW', '3-Series Sedan'),
('BMW', '3-Series Touring'),
('BMW', '5-Series'),
('BMW', '5-Series GT'),
('BMW', '6-Series'),
('BMW', '7-Series'),
('BMW', '8-Series'),
('BMW', 'M Coupe'),
('BMW', 'M1'),
('BMW', 'M3'),
('BMW', 'M5'),
('BMW', 'M6'),
('BMW', 'X1'),
('BMW', 'X3'),
('BMW', 'X5'),
('BMW', 'X6'),
('BMW', 'Z1'),
('BMW', 'Z3'),
('BMW', 'Z4'),
('BMW', 'Z8'),
('Bristol', '412'),
('Bristol', '603'),
('Bristol', 'Beaufighter'),
('Bristol', 'Blenheim'),
('Bristol', 'Brigand'),
('Bristol', 'Britannia'),
('Buick', 'Riviera'),
('Cadillac', 'BLS'),
('Cadillac', 'CTS'),
('Cadillac', 'CTS V-Series'),
('Cadillac', 'DTS'),
('Cadillac', 'Escalade ESV'),
('Cadillac', 'Escalade EXT'),
('Cadillac', 'Escalade SUV'),
('Cadillac', 'Seville'),
('Cadillac', 'SRX'),
('Cadillac', 'STS V-Series'),
('Cadillac', 'XLR V-Series'),
('CAM', 'Inyathi'),
('CAM', 'Rhino'),
('Caterham', 'Super Seven'),
('Chana', 'Benni'),
('Chana', 'Club Cab'),
('Chana', 'Double Cab'),
('Chana', 'Drop Side'),
('Chana', 'Panel Van'),
('Chana', 'Rainbow'),
('Chana', 'Single Cab'),
('Chana', 'Star'),
('Cherry', 'J1'),
('Cherry', 'J5'),
('Cherry', 'QQ'),
('Cherry', 'Tiggo'),
('Chevrolet', 'Blazer'),
('Chevrolet', 'Camarro'),
('Chevrolet', 'Captiva'),
('Chevrolet', 'Corvette'),
('Chevrolet', 'Cruze'),
('Chevrolet', 'Grand Voyager'),
('Chevrolet', 'Lumina'),
('Chevrolet', 'Optra'),
('Chevrolet', 'Spark'),
('Chevrolet', 'Vivant'),
('Chrysler', '180'),
('Chrysler', '2-Litre'),
('Chrysler', '300C'),
('Chrysler', 'Avenger'),
('Chrysler', 'Charger'),
('Chrysler', 'Crossfire'),
('Chrysler', 'Grand Voyager'),
('Chrysler', 'Neon'),
('Chrysler', 'New Yorker'),
('Chrysler', 'Optra'),
('Chrysler', 'PT Cruiser'),
('Chrysler', 'Sebring'),
('Chrysler', 'Spark'),
('Chrysler', 'Valiant'),
('Chrysler', 'Viper'),
('Chrysler', 'Voyager'),
('Citroen', '2 CV6'),
('Citroen', 'Athena'),
('Citroen', 'AX'),
('Citroen', 'Berlingo'),
('Citroen', 'BX'),
('Citroen', 'C1'),
('Citroen', 'C2'),
('Citroen', 'C3'),
('Citroen', 'C4'),
('Citroen', 'C5'),
('Citroen', 'CX'),
('Citroen', 'CX20'),
('Citroen', 'CX2400'),
('Citroen', 'CX2500'),
('Citroen', 'CX25D'),
('Citroen', 'Dyane'),
('Citroen', 'GSA'),
('Citroen', 'LNA'),
('Citroen', 'Picasso'),
('Citroen', 'Reflex'),
('Citroen', 'Saxo'),
('Citroen', 'Synergie'),
('Citroen', 'Visa'),
('Citroen', 'Xantia'),
('Citroen', 'XM'),
('Citroen', 'Xsara'),
('Citroen', 'Xsara Picasso'),
('Citroen', 'ZX'),
('CMC', 'Amandla'),
('CMC', 'Auto Union'),
('CMC', 'Horch'),
('Dacia', 'Denem'),
('Dacia', 'Duster'),
('Daewoo', 'Cielo'),
('Daewoo', 'Espero'),
('Daewoo', 'Korando'),
('Daewoo', 'Lanos'),
('Daewoo', 'Leganza'),
('Daewoo', 'Matiz'),
('Daewoo', 'Musso'),
('Daewoo', 'Nexia'),
('Daewoo', 'Nubira'),
('Daewoo', 'Tacuma'),
('Daihatsu', 'Applause'),
('Daihatsu', 'Charade'),
('Daihatsu', 'Charmant'),
('Daihatsu', 'Copen'),
('Daihatsu', 'Cuore'),
('Daihatsu', 'Domino'),
('Daihatsu', 'Fortrak'),
('Daihatsu', 'Gran Max'),
('Daihatsu', 'Grand Move'),
('Daihatsu', 'Hijet'),
('Daihatsu', 'Materia'),
('Daihatsu', 'Mira'),
('Daihatsu', 'Move'),
('Daihatsu', 'Rocky'),
('Daihatsu', 'Sirion'),
('Daihatsu', 'Sportrak'),
('Daihatsu', 'Terios'),
('Daihatsu', 'YRV'),
('Daimler', 'Limousine'),
('Daimler', 'Series III'),
('Daimler', 'Sovereign'),
('Daimler', 'XJ Series'),
('Datsun', '120Y'),
('Datsun', '280L'),
('De Tomaso', 'Guara'),
('De Tomaso', 'Pantera'),
('DFM', 'Mini Cargo Van'),
('DFM', 'Mini Panel Van'),
('DFM', 'Mini Truck'),
('Dodge', 'Caliber'),
('Dodge', 'Journey'),
('Dodge', 'Nitro'),
('Dodge', 'Ram'),
('Dodge', 'Viper'),
('Ferrari', '308'),
('Ferrari', '328'),
('Ferrari', '348'),
('Ferrari', '360'),
('Ferrari', '400'),
('Ferrari', '412'),
('Ferrari', '456'),
('Ferrari', '512'),
('Ferrari', '550'),
('Ferrari', '559 GTB'),
('Ferrari', '612 Scaglietti'),
('Ferrari', 'California'),
('Ferrari', 'F355'),
('Ferrari', 'F40'),
('Ferrari', 'F430'),
('Ferrari', 'F50'),
('Ferrari', 'F512'),
('Ferrari', 'FXX'),
('Ferrari', 'Mondial'),
('Ferrari', 'Testarossa'),
('Fiat', '126'),
('Fiat', '127'),
('Fiat', '128'),
('Fiat', '131'),
('Fiat', '132'),
('Fiat', '500'),
('Fiat', 'Abarth'),
('Fiat', 'Argenta'),
('Fiat', 'Barcheta'),
('Fiat', 'Brava'),
('Fiat', 'Bravo'),
('Fiat', 'Cinquecento'),
('Fiat', 'Coupe'),
('Fiat', 'Croma'),
('Fiat', 'Doblo'),
('Fiat', 'Doblo cargo'),
('Fiat', 'Ducato'),
('Fiat', 'Everest'),
('Fiat', 'Linea'),
('Fiat', 'Marea'),
('Fiat', 'Marea Weekend'),
('Fiat', 'Multipla'),
('Fiat', 'Palio'),
('Fiat', 'Panda'),
('Fiat', 'Punto'),
('Fiat', 'Regata'),
('Fiat', 'Scudo'),
('Fiat', 'Seicento'),
('Fiat', 'Siena'),
('Fiat', 'Stilo'),
('Fiat', 'Strada'),
('Fiat', 'Tempra'),
('Fiat', 'Tipo'),
('Fiat', 'Ulysse'),
('Fiat', 'Uno'),
('Fiat', 'Weekend'),
('Fiat', 'X1/9'),
('Ford', 'Anglia'),
('Ford', 'Bantam'),
('Ford', 'Capri'),
('Ford', 'Cortina'),
('Ford', 'Cougar'),
('Ford', 'Courier'),
('Ford', 'Escort'),
('Ford', 'Explorer'),
('Ford', 'F-Series'),
('Ford', 'Fairlane'),
('Ford', 'Fairmont'),
('Ford', 'Falcon'),
('Ford', 'Fiesta'),
('Ford', 'Focus'),
('Ford', 'Futura'),
('Ford', 'Galaxy'),
('Ford', 'Granada'),
('Ford', 'Husky'),
('Ford', 'Ikon'),
('Ford', 'Ka'),
('Ford', 'Laser'),
('Ford', 'Maverick'),
('Ford', 'Meteor'),
('Ford', 'Mondeo'),
('Ford', 'Mustang'),
('Ford', 'Orion'),
('Ford', 'Probe'),
('Ford', 'Puma'),
('Ford', 'Ranchero'),
('Ford', 'Ranger'),
('Ford', 'Sapphire'),
('Ford', 'Scorpio'),
('Ford', 'Sierra'),
('Ford', 'Spectron'),
('Ford', 'Telstar'),
('Ford', 'Territory'),
('Ford', 'Tracer'),
('Ford', 'TX5'),
('Foton', 'Foton View Panel Van'),
('FSO', '125P'),
('FSO', '1300'),
('FSO', 'Caro'),
('FSO', 'Polonez'),
('Fudi', 'Lion'),
('Geely', 'CK1'),
('Geely', 'MK'),
('Geely', 'MK2'),
('GMC', 'Typhoon'),
('GoNow', 'Luxury Double Cab'),
('GoNow', 'Luxury Double Cab 2.2iL'),
('GoNow', 'Luxury LWB Double Cab'),
('GoNow', 'Luxury LWB Double Cab 2.2iXL'),
('GoNow', 'Luxury Single Cab'),
('GoNow', 'Luxury Single Cab 2.2iL'),
('GoNow', 'Standard Double Cab'),
('GoNow', 'Standard Double Cab 2.2i'),
('GoNow', 'Standard LWB Double Cab'),
('GoNow', 'Standard LWB Double Cab 2.2iX'),
('GoNow', 'Standard Single Cab'),
('GoNow', 'Standard Single Cab 2.2i'),
('GoNow', 'X-Space'),
('GWM', 'Double Cab Lux'),
('GWM', 'Florid'),
('GWM', 'Hover'),
('GWM', 'Multi-wagon'),
('GWM', 'Single Cab Lux'),
('GWM', 'Single Cab Std'),
('GWM', 'Steed'),
('Hafei', 'Loda'),
('HMC', 'Lightweight'),
('HMC', 'MK IV'),
('Honda', 'Accord'),
('Honda', 'Aerodeck'),
('Honda', 'Ballad'),
('Honda', 'Civic'),
('Honda', 'Concerto'),
('Honda', 'CR-V'),
('Honda', 'CR-X'),
('Honda', 'FR-V'),
('Honda', 'HR-V'),
('Honda', 'Insight'),
('Honda', 'Integra'),
('Honda', 'Jazz'),
('Honda', 'Legend'),
('Honda', 'Logo'),
('Honda', 'NSX'),
('Honda', 'Odyssey'),
('Honda', 'Prelude'),
('Honda', 'Quintet'),
('Honda', 'S2000'),
('Honda', 'Shuttle'),
('Honda', 'Stream'),
('Hummer', 'H1'),
('Hummer', 'H2'),
('Hummer', 'H3'),
('Hyundai', 'Accent'),
('Hyundai', 'Amica'),
('Hyundai', 'Atos'),
('Hyundai', 'Azera'),
('Hyundai', 'Coupe'),
('Hyundai', 'Elantra'),
('Hyundai', 'Getz'),
('Hyundai', 'H1'),
('Hyundai', 'H10'),
('Hyundai', 'H100'),
('Hyundai', 'i10'),
('Hyundai', 'i20'),
('Hyundai', 'Matrix'),
('Hyundai', 'Pony'),
('Hyundai', 'Pony X2'),
('Hyundai', 'Santa Fe'),
('Hyundai', 'Scoupe'),
('Hyundai', 'Sonata'),
('Hyundai', 'Stellar'),
('Hyundai', 'Terracan'),
('Hyundai', 'Tiburon'),
('Hyundai', 'Trajet'),
('Hyundai', 'Tucson'),
('Hyundai', 'XG30'),
('Imperial', ''),
('Isuzu', 'Frontier'),
('Isuzu', 'KB Series'),
('Isuzu', 'Piazza'),
('Isuzu', 'Relay Bus'),
('Isuzu', 'Trooper'),
('Jaguar', 'S-Type'),
('Jaguar', 'Sovereign'),
('Jaguar', 'X-Type'),
('Jaguar', 'XF'),
('Jaguar', 'XJ'),
('Jaguar', 'XJ12'),
('Jaguar', 'XJ220'),
('Jaguar', 'XJ6'),
('Jaguar', 'XJ8'),
('Jaguar', 'XJR'),
('Jaguar', 'XJS'),
('Jaguar', 'XK8'),
('Jaguar', 'XKR'),
('Jeep', 'Cherokee'),
('Jeep', 'Commander'),
('Jeep', 'Compass'),
('Jeep', 'Grand Cherokee'),
('Jeep', 'Patriot'),
('Jeep', 'Wrangler'),
('Jenson', 'Inspector SP'),
('Karma', 'Ghia'),
('Kia', 'Carens'),
('Kia', 'Carnival'),
('Kia', 'Cerato'),
('Kia', 'Clarus'),
('Kia', 'Magentis'),
('Kia', 'Mentor'),
('Kia', 'Picanto'),
('Kia', 'Pregio'),
('Kia', 'Pride'),
('Kia', 'Rio'),
('Kia', 'Sedona'),
('Kia', 'Shuma'),
('Kia', 'Sorento'),
('Kia', 'Soul'),
('Kia', 'Spectra'),
('Kia', 'Sportage'),
('Lada', 'Niva'),
('Lada', 'Riva'),
('Lada', 'Samara'),
('Lamborghini', 'Countach'),
('Lamborghini', 'Diablo'),
('Lamborghini', 'Gallardo'),
('Lamborghini', 'Murcielago'),
('Lancia', 'Beta'),
('Lancia', 'Dedra'),
('Lancia', 'Delta'),
('Lancia', 'Gamma'),
('Lancia', 'Monte Carlo'),
('Lancia', 'Prisma'),
('Lancia', 'Thema'),
('Lancia', 'Trevi'),
('Lancia', 'Wippet'),
('Lancia', 'Y10'),
('Land Rover', 'Defender 110'),
('Land Rover', 'Defender 90'),
('Land Rover', 'Defender Cup'),
('Land Rover', 'Discovery'),
('Land Rover', 'Freelander'),
('Land Rover', 'Range Rover'),
('Lexus', 'GS'),
('Lexus', 'GS 300'),
('Lexus', 'GS 430'),
('Lexus', 'GS 450h'),
('Lexus', 'IS'),
('Lexus', 'IS 200'),
('Lexus', 'IS 250'),
('Lexus', 'IS 300'),
('Lexus', 'LS'),
('Lexus', 'LS 400'),
('Lexus', 'LS 430'),
('Lexus', 'LX 46'),
('Lexus', 'LX 470'),
('Lexus', 'RX'),
('Lexus', 'RX 300'),
('Lexus', 'RX 350'),
('Lexus', 'RX 400h'),
('Lexus', 'SC'),
('Lexus', 'SC 430'),
('Leyland', 'Mini'),
('Ligier', 'Ambra'),
('Lincoln', 'Continental'),
('Lonsdale', 'YD41'),
('Lonsdale', 'YD45'),
('Lotus', 'Eclat'),
('Lotus', 'Elan'),
('Lotus', 'Elise'),
('Lotus', 'Elite'),
('Lotus', 'Esprit'),
('Lotus', 'Europa'),
('Lotus', 'Evora'),
('Lotus', 'Excel'),
('Lotus', 'Exige'),
('Lynx', 'Roadster'),
('M.G.', 'MGB'),
('M.G.', 'MGF'),
('M.G.', 'Midget'),
('M.G.', 'RV8'),
('M.G.', 'TF'),
('M.G.', 'ZR'),
('M.G.', 'ZS'),
('M.G.', 'ZT'),
('Mahindra', 'Bolero'),
('Mahindra', 'Scorpio'),
('Mahindra', 'Thar'),
('Mahindra', 'Xylo'),
('Mandarin', 'Soyat'),
('Maserati', '222'),
('Maserati', '3200'),
('Maserati', '430'),
('Maserati', 'Biturbo'),
('Maserati', 'Coupe'),
('Maserati', 'Ghibli'),
('Maserati', 'Gran Turismo'),
('Maserati', 'GranSport'),
('Maserati', 'Quattroporte'),
('Maserati', 'Shamal'),
('Maserati', 'Spyder'),
('Maybach', '57'),
('Maybach', '62'),
('Mazda', '121'),
('Mazda', '2'),
('Mazda', '3'),
('Mazda', '323'),
('Mazda', '5'),
('Mazda', '6'),
('Mazda', '626'),
('Mazda', '929'),
('Mazda', 'Austina'),
('Mazda', 'B250'),
('Mazda', 'BT50'),
('Mazda', 'CX7'),
('Mazda', 'Demio'),
('Mazda', 'Drifter'),
('Mazda', 'Etude'),
('Mazda', 'Magnum'),
('Mazda', 'Marathon'),
('Mazda', 'Midge'),
('Mazda', 'MPV'),
('Mazda', 'MX-3'),
('Mazda', 'MX-5'),
('Mazda', 'MX-6'),
('Mazda', 'Premacy'),
('Mazda', 'RX-7'),
('Mazda', 'RX-8'),
('Mazda', 'Soho'),
('Mazda', 'Sting'),
('Mazda', 'Xedos 6'),
('Mazda', 'Xedos 9'),
('Meiya', 'Pickup'),
('Mercedes Benz', '115'),
('Mercedes Benz', '190'),
('Mercedes Benz', '190E'),
('Mercedes Benz', '200'),
('Mercedes Benz', '200E'),
('Mercedes Benz', '220'),
('Mercedes Benz', '220E'),
('Mercedes Benz', '230'),
('Mercedes Benz', '230E'),
('Mercedes Benz', '240'),
('Mercedes Benz', '250'),
('Mercedes Benz', '260'),
('Mercedes Benz', '260E'),
('Mercedes Benz', '280'),
('Mercedes Benz', '280E'),
('Mercedes Benz', '300'),
('Mercedes Benz', '300CE'),
('Mercedes Benz', '300E'),
('Mercedes Benz', '300SE'),
('Mercedes Benz', '300TE'),
('Mercedes Benz', '320'),
('Mercedes Benz', '320E'),
('Mercedes Benz', '380'),
('Mercedes Benz', '400'),
('Mercedes Benz', '420'),
('Mercedes Benz', '500'),
('Mercedes Benz', '500SE'),
('Mercedes Benz', '560'),
('Mercedes Benz', '600'),
('Mercedes Benz', 'A-Class'),
('Mercedes Benz', 'B-Class'),
('Mercedes Benz', 'C Coupe'),
('Mercedes Benz', 'C-Class'),
('Mercedes Benz', 'CL-Class'),
('Mercedes Benz', 'CLC'),
('Mercedes Benz', 'CLK'),
('Mercedes Benz', 'CLS'),
('Mercedes Benz', 'CLS-Class'),
('Mercedes Benz', 'E-Class'),
('Mercedes Benz', 'GL-Class'),
('Mercedes Benz', 'M-Class'),
('Mercedes Benz', 'R-Class'),
('Mercedes Benz', 'S-65'),
('Mercedes Benz', 'S-Class'),
('Mercedes Benz', 'SL-Class'),
('Mercedes Benz', 'SLS'),
('Mercedes Benz', 'Viano'),
('Mercedes Benz', 'Vito'),
('Mercury', ''),
('Mini', 'Austin'),
('Mini', 'Checkmate'),
('Mini', 'Cooper'),
('Mini', 'Cooper S'),
('Mini', 'Mini'),
('Mini', 'Park Lane'),
('Mini', 'Seven'),
('Mitsubishi', '3000 GT'),
('Mitsubishi', 'Carisma'),
('Mitsubishi', 'Celeste'),
('Mitsubishi', 'Challenger'),
('Mitsubishi', 'Colt'),
('Mitsubishi', 'Cordia'),
('Mitsubishi', 'FTO'),
('Mitsubishi', 'Galant'),
('Mitsubishi', 'L300'),
('Mitsubishi', 'Lancer'),
('Mitsubishi', 'Outlander'),
('Mitsubishi', 'Pajero'),
('Mitsubishi', 'Sapporro'),
('Mitsubishi', 'Shogun'),
('Mitsubishi', 'Sigma'),
('Mitsubishi', 'Space Gear'),
('Mitsubishi', 'Space Runner'),
('Mitsubishi', 'Space Wagon'),
('Mitsubishi', 'Starion'),
('Mitsubishi', 'Tredia'),
('Mitsubishi', 'Triton'),
('Morgan', '4/4'),
('Morgan', 'Aero 8'),
('Morgan', 'Plus 4'),
('Morgan', 'Plus 8'),
('Morgan', 'Roadster'),
('Morris', 'Ital'),
('Morris', 'Marina'),
('Nissan', '100NX'),
('Nissan', '1400'),
('Nissan', '1400 Champ'),
('Nissan', '200'),
('Nissan', '200SX'),
('Nissan', '280C'),
('Nissan', '280ZX'),
('Nissan', '300'),
('Nissan', '300ZX'),
('Nissan', '350Z'),
('Nissan', '370Z'),
('Nissan', 'Almera'),
('Nissan', 'Almera Tino'),
('Nissan', 'Bluebird'),
('Nissan', 'Cherry'),
('Nissan', 'E20'),
('Nissan', 'Grand Livina'),
('Nissan', 'GTR'),
('Nissan', 'Hardbody'),
('Nissan', 'Laurel'),
('Nissan', 'Livina'),
('Nissan', 'Maxima'),
('Nissan', 'Micra'),
('Nissan', 'Murano'),
('Nissan', 'Navara'),
('Nissan', 'NP2000'),
('Nissan', 'Pathfinder'),
('Nissan', 'Patrol'),
('Nissan', 'Prairie'),
('Nissan', 'Primastar'),
('Nissan', 'Primera'),
('Nissan', 'QashQai Acenta'),
('Nissan', 'QashQai Visia'),
('Nissan', 'QX'),
('Nissan', 'Sabre'),
('Nissan', 'Sani'),
('Nissan', 'Sentra'),
('Nissan', 'Serena'),
('Nissan', 'Skyline'),
('Nissan', 'Stanza'),
('Nissan', 'Sunny'),
('Nissan', 'Sylvia'),
('Nissan', 'Terrano'),
('Nissan', 'Tiida'),
('Nissan', 'Xtrail'),
('Noble', 'M12 GTO-3R'),
('Noble', 'M15'),
('Noble', 'M400'),
('NP', '200'),
('NP', 'NP'),
('Opel', 'Astra'),
('Opel', 'Commodore'),
('Opel', 'Corsa'),
('Opel', 'Estate'),
('Opel', 'Kadett'),
('Opel', 'Manta'),
('Opel', 'Meriva'),
('Opel', 'Monza'),
('Opel', 'Omega'),
('Opel', 'Rekord'),
('Opel', 'Senator'),
('Opel', 'Tigra'),
('Opel', 'Vivaro'),
('Opel', 'Zafira'),
('Peugeot', '1007'),
('Peugeot', '104'),
('Peugeot', '106'),
('Peugeot', '107'),
('Peugeot', '205'),
('Peugeot', '206'),
('Peugeot', '207'),
('Peugeot', '3008'),
('Peugeot', '304'),
('Peugeot', '305'),
('Peugeot', '306'),
('Peugeot', '307'),
('Peugeot', '308'),
('Peugeot', '309'),
('Peugeot', '405'),
('Peugeot', '406'),
('Peugeot', '407'),
('Peugeot', '504'),
('Peugeot', '505'),
('Peugeot', '604'),
('Peugeot', '605'),
('Peugeot', '607'),
('Peugeot', '806'),
('Peugeot', '807'),
('Peugeot', 'Partner'),
('Plymouth', '68 Road Runner'),
('Plymouth', '70 AAR Cuda'),
('Plymouth', '70 Cuda'),
('Plymouth', '70 Cuda 340'),
('Plymouth', '70 Road Runner'),
('Plymouth', '71 Road Runner 440'),
('Pontiac', 'Firebird'),
('Pontiac', 'Trans Am'),
('Porsche', '356'),
('Porsche', '911'),
('Porsche', '912'),
('Porsche', '914'),
('Porsche', '924'),
('Porsche', '928'),
('Porsche', '944'),
('Porsche', '959'),
('Porsche', '968'),
('Porsche', '996'),
('Porsche', 'Boxster'),
('Porsche', 'Boxster S'),
('Porsche', 'Carrera'),
('Porsche', 'Cayenne'),
('Porsche', 'Cayman'),
('Porsche', 'GT2'),
('Porsche', 'GT3'),
('Porsche', 'GT3 RS'),
('Porsche', 'Panamera'),
('Proton', 'Arena'),
('Proton', 'Compact'),
('Proton', 'Coupe'),
('Proton', 'Gen.2'),
('Proton', 'Impian'),
('Proton', 'Jumbuck'),
('Proton', 'Persona'),
('Proton', 'Persona Compact'),
('Proton', 'Satria'),
('Proton', 'Savvy'),
('Proton', 'Wira'),
('Rambler', ''),
('Reliant', 'Kitten'),
('Reliant', 'Rialto 2'),
('Reliant', 'Robin'),
('Reliant', 'Sabre'),
('Reliant', 'Scimitar'),
('Reliant', 'Scimitar SST'),
('Reliant', 'SS1'),
('Renault', '11'),
('Renault', '12'),
('Renault', '14'),
('Renault', '15'),
('Renault', '16'),
('Renault', '17'),
('Renault', '18'),
('Renault', '19'),
('Renault', '20'),
('Renault', '21'),
('Renault', '25'),
('Renault', '30'),
('Renault', '4'),
('Renault', '5'),
('Renault', '6'),
('Renault', '9'),
('Renault', 'A610'),
('Renault', 'Clio'),
('Renault', 'Espace'),
('Renault', 'Fuego'),
('Renault', 'Grand Espace'),
('Renault', 'Grand Scenic'),
('Renault', 'GTA'),
('Renault', 'Kangoo'),
('Renault', 'Koleos'),
('Renault', 'Laguna'),
('Renault', 'Logan'),
('Renault', 'Megane'),
('Renault', 'Megane Scenic'),
('Renault', 'Modus'),
('Renault', 'Safrane'),
('Renault', 'Sandero'),
('Renault', 'Scenic'),
('Renault', 'Scenic RX4'),
('Renault', 'Sport Spider'),
('Renault', 'Twingo'),
('Renault', 'Vel Satis'),
('Rolls Royce', 'Camargue'),
('Rolls Royce', 'Corniche'),
('Rolls Royce', 'Flying Spur'),
('Rolls Royce', 'Limousine'),
('Rolls Royce', 'Park Ward'),
('Rolls Royce', 'Phantom VI'),
('Rolls Royce', 'Silver Dawn'),
('Rolls Royce', 'Silver Seraph'),
('Rolls Royce', 'Silver Shadow'),
('Rolls Royce', 'Silver Spirit'),
('Rolls Royce', 'Silver Spur'),
('Rolls Royce', 'Silver Wraith'),
('Rover', '100'),
('Rover', '200'),
('Rover', '2000'),
('Rover', '2300'),
('Rover', '2400'),
('Rover', '25'),
('Rover', '2600'),
('Rover', '3500'),
('Rover', '400'),
('Rover', '45'),
('Rover', '600'),
('Rover', '75'),
('Rover', '800'),
('Rover', 'Cabriolet'),
('Rover', 'Coupe'),
('Rover', 'Metro'),
('Rover', 'Tourer'),
('Saab', '9-3'),
('Saab', '9-5'),
('Saab', '90'),
('Saab', '900'),
('Saab', '9000'),
('Saab', '99'),
('Seat', 'Alhambra'),
('Seat', 'Altea'),
('Seat', 'Cupra'),
('Seat', 'Ibiza'),
('Seat', 'Leon'),
('Seat', 'Toledo'),
('Smart', 'Cabrio'),
('Smart', 'City Coupe'),
('Smart', 'ForFour'),
('Smart', 'ForTwo'),
('Smart', 'Passion'),
('Smart', 'Pulse'),
('Smart', 'Pure'),
('Smart', 'Roadster'),
('Ssangyong', 'Actyon'),
('Ssangyong', 'Korando'),
('Ssangyong', 'Kyron'),
('Ssangyong', 'Musso'),
('Ssangyong', 'Rexton'),
('Ssangyong', 'Stavic'),
('Stude', 'Baker'),
('Studebaker', 'Phaeton'),
('Subaru', '1600'),
('Subaru', '1800'),
('Subaru', 'Forester'),
('Subaru', 'Impreza'),
('Subaru', 'Justy'),
('Subaru', 'Legacy'),
('Subaru', 'Outback'),
('Subaru', 'SVX'),
('Subaru', 'Tribeca'),
('Subaru', 'Vivio'),
('Subaru', 'WRX'),
('Sunbeam', 'Jenson'),
('Sunbeam', 'Plymouth'),
('Suzuki', 'Alto'),
('Suzuki', 'Grand Vitara'),
('Suzuki', 'Jimny'),
('Suzuki', 'Liana'),
('Suzuki', 'Samurai'),
('Suzuki', 'SC100'),
('Suzuki', 'SJ'),
('Suzuki', 'Swift'),
('Suzuki', 'SX4'),
('Suzuki', 'Vitara'),
('Suzuki', 'Wagon R+'),
('Suzuki', 'X90'),
('Tata', 'B-Line'),
('Tata', 'Indica'),
('Tata', 'Indigo'),
('Tata', 'Safari'),
('Tata', 'Telcoline'),
('Tata', 'Xenon'),
('Toyota', '4 Runner'),
('Toyota', 'Auris'),
('Toyota', 'Avanza'),
('Toyota', 'Avensis'),
('Toyota', 'Camry'),
('Toyota', 'Carina'),
('Toyota', 'Carina E'),
('Toyota', 'Carri'),
('Toyota', 'Celica'),
('Toyota', 'Condor'),
('Toyota', 'Conquest'),
('Toyota', 'Corolla'),
('Toyota', 'Corona'),
('Toyota', 'Cressida'),
('Toyota', 'Crown'),
('Toyota', 'Fortuner'),
('Toyota', 'Hi-Ace'),
('Toyota', 'Hilux'),
('Toyota', 'Land Cruiser'),
('Toyota', 'MR2'),
('Toyota', 'Paseo'),
('Toyota', 'Picnic'),
('Toyota', 'Prado'),
('Toyota', 'Previa'),
('Toyota', 'Prius'),
('Toyota', 'Quantum'),
('Toyota', 'Rav 4'),
('Toyota', 'RunX'),
('Toyota', 'Space Cruiser'),
('Toyota', 'Sprinter'),
('Toyota', 'Stallion Commutor'),
('Toyota', 'Starlet'),
('Toyota', 'Supra'),
('TVR', '2500M'),
('TVR', '280i'),
('TVR', '3000'),
('TVR', '3000M'),
('TVR', '350i'),
('TVR', '390'),
('TVR', '400'),
('TVR', '420'),
('TVR', '450'),
('TVR', 'Cerbera'),
('TVR', 'Chimaera'),
('TVR', 'Griffith'),
('TVR', 'S'),
('TVR', 'S2'),
('TVR', 'S3'),
('TVR', 'S4c'),
('TVR', 'Sagaris'),
('TVR', 'Speed 8'),
('TVR', 'T350'),
('TVR', 'T350c'),
('TVR', 'T350t'),
('TVR', 'Taimar'),
('TVR', 'Tamora'),
('TVR', 'Tasmin'),
('TVR', 'Tuscan'),
('TVR', 'Typhon'),
('TVR', 'V8');
